apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-product
  template:
    metadata:
      labels:
        app: ms-product
    spec:
      containers:
        - name: ms-product
          image: RaildoBru/fiap-tech-challenge-product
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              value: ${MONGO_URI}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-product
spec:
  type: LoadBalancer
  selector:
    app: ms-product
  ports:
    - port: 8080
      targetPort: 5002
